name: Release PZ Web Config App

on:
  release:
    types: [created] # 当你创建一个新的 Release 时触发

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # 只编译 Linux amd64
        goos: [linux]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.25.5'

    - name: Build Binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        # 这里的 main.Version 要对应 package main
        go build -v -ldflags "-X main.Version=${{ github.ref_name }} -X main.BuildTime=$(date -u +%Y-%m-%dT%H:%M:%SZ)" -o pz-config-app-${{ matrix.goos }}-${{ matrix.goarch }} pz-web-config/main.go

    - name: Upload Release Assets
      uses: softprops/action-gh-release@v1
      with:
        files: pz-config-app-${{ matrix.goos }}-${{ matrix.goarch }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}